# Generated by Django 3.2.6 on 2021-10-22 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='calculate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number1', models.IntegerField(null=True)),
                ('number2', models.IntegerField(null=True)),
                ('answer', models.IntegerField(null=True)),
            ],
        ),
    ]
